/**
 * BuntesBegegnen.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Activity } from '../models/Activity';
import { HttpFile } from '../http/http';

export class ActivityRecurrenceDate {
    'activityId': number;
    'activity'?: Activity;
    'startTime': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activityId",
            "baseName": "activityId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "activity",
            "baseName": "activity",
            "type": "Activity",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ActivityRecurrenceDate.attributeTypeMap;
    }

    public constructor() {
    }
}
