/**
 * BuntesBegegnen.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DayOfWeek } from '../models/DayOfWeek';
import { HttpFile } from '../http/http';

export class ActivityRecurrenceByDayDto {
    'ordinal'?: number;
    'dayOfWeek'?: DayOfWeek;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dayOfWeek",
            "baseName": "dayOfWeek",
            "type": "DayOfWeek",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActivityRecurrenceByDayDto.attributeTypeMap;
    }

    public constructor() {
    }
}


