/**
 * BuntesBegegnen.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidationConstraintType } from '../models/ValidationConstraintType';
import { HttpFile } from '../http/http';

export class FieldValidationConstraintDto {
    'type'?: ValidationConstraintType;
    'constraint'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ValidationConstraintType",
            "format": ""
        },
        {
            "name": "constraint",
            "baseName": "constraint",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FieldValidationConstraintDto.attributeTypeMap;
    }

    public constructor() {
    }
}


