/**
 * BuntesBegegnen.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Activity } from '../models/Activity';
import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class Promoter {
    'id'?: number;
    'createdAt': Date;
    'createdById': string | null;
    'createdBy'?: User;
    'isDeleted'?: boolean;
    'name': string;
    'website': string | null;
    'streetName': string | null;
    'houseNumber': string | null;
    'zipCode': string | null;
    'city': string | null;
    'activities'?: Array<Activity>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdById",
            "baseName": "createdById",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "User",
            "format": ""
        },
        {
            "name": "isDeleted",
            "baseName": "isDeleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "string",
            "format": ""
        },
        {
            "name": "streetName",
            "baseName": "streetName",
            "type": "string",
            "format": ""
        },
        {
            "name": "houseNumber",
            "baseName": "houseNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "zipCode",
            "baseName": "zipCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "activities",
            "baseName": "activities",
            "type": "Array<Activity>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Promoter.attributeTypeMap;
    }

    public constructor() {
    }
}
