/**
 * BuntesBegegnen.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FieldValidationConstraintDto } from '../models/FieldValidationConstraintDto';
import { HttpFile } from '../http/http';

export class TypeConstraintsDto {
    'fields'?: { [key: string]: Array<FieldValidationConstraintDto>; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "{ [key: string]: Array<FieldValidationConstraintDto>; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TypeConstraintsDto.attributeTypeMap;
    }

    public constructor() {
    }
}
