/**
 * BuntesBegegnen.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Promoter } from '../models/Promoter';
import { UserFavoriteCategory } from '../models/UserFavoriteCategory';
import { HttpFile } from '../http/http';

export class User {
    'id'?: string;
    'userName'?: string | null;
    'normalizedUserName'?: string | null;
    'email'?: string | null;
    'normalizedEmail'?: string | null;
    'emailConfirmed'?: boolean;
    'passwordHash'?: string | null;
    'securityStamp'?: string | null;
    'concurrencyStamp'?: string | null;
    'phoneNumber'?: string | null;
    'phoneNumberConfirmed'?: boolean;
    'twoFactorEnabled'?: boolean;
    'lockoutEnd'?: Date | null;
    'lockoutEnabled'?: boolean;
    'accessFailedCount'?: number;
    'createdAt': Date;
    'firstName': string;
    'lastName': string;
    'birthDay'?: string | null;
    'streetName'?: string | null;
    'houseNumber'?: string | null;
    'zipCode'?: string | null;
    'city'?: string | null;
    'promoterId'?: number | null;
    'promoter'?: Promoter;
    'goals'?: string | null;
    'hobbies'?: string | null;
    'favoriteCategories'?: Array<UserFavoriteCategory>;
    'impairedSight'?: boolean;
    'impairedHearing'?: boolean;
    'impairedSpeech'?: boolean;
    'impairedMobility'?: boolean;
    'additionalHandicaps'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "normalizedUserName",
            "baseName": "normalizedUserName",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "normalizedEmail",
            "baseName": "normalizedEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailConfirmed",
            "baseName": "emailConfirmed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "passwordHash",
            "baseName": "passwordHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "securityStamp",
            "baseName": "securityStamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "concurrencyStamp",
            "baseName": "concurrencyStamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumberConfirmed",
            "baseName": "phoneNumberConfirmed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "twoFactorEnabled",
            "baseName": "twoFactorEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lockoutEnd",
            "baseName": "lockoutEnd",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lockoutEnabled",
            "baseName": "lockoutEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "accessFailedCount",
            "baseName": "accessFailedCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthDay",
            "baseName": "birthDay",
            "type": "string",
            "format": "date"
        },
        {
            "name": "streetName",
            "baseName": "streetName",
            "type": "string",
            "format": ""
        },
        {
            "name": "houseNumber",
            "baseName": "houseNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "zipCode",
            "baseName": "zipCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "promoterId",
            "baseName": "promoterId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "promoter",
            "baseName": "promoter",
            "type": "Promoter",
            "format": ""
        },
        {
            "name": "goals",
            "baseName": "goals",
            "type": "string",
            "format": ""
        },
        {
            "name": "hobbies",
            "baseName": "hobbies",
            "type": "string",
            "format": ""
        },
        {
            "name": "favoriteCategories",
            "baseName": "favoriteCategories",
            "type": "Array<UserFavoriteCategory>",
            "format": ""
        },
        {
            "name": "impairedSight",
            "baseName": "impairedSight",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "impairedHearing",
            "baseName": "impairedHearing",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "impairedSpeech",
            "baseName": "impairedSpeech",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "impairedMobility",
            "baseName": "impairedMobility",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "additionalHandicaps",
            "baseName": "additionalHandicaps",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}
