/**
 * BuntesBegegnen.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActivityCategory } from '../models/ActivityCategory';
import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class UserFavoriteCategory {
    'userId': string;
    'user'?: User;
    'category': ActivityCategory;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "ActivityCategory",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserFavoriteCategory.attributeTypeMap;
    }

    public constructor() {
    }
}


